return {
	{{name = "power-armor", count = 1}},
	{
		{name = "flamethrower", count = 1},
		{name = "flamethrower-ammo", count = 50},
	},
	{{name = "gun-turret", count = 10}},
	{{name = "repair-pack", count = 100}},
	{
		{name = "stone-wall", count = 190},
		{name = "gate", count = 10},
	},
	{{name = "construction-robot", count = 20}},
	{{name = "defender-capsule", count = 20}},
	{{name = "distractor-capsule", count = 9}},
	{{name = "destroyer-capsule", count = 3}},
	{{name = "cannon-shell", count = 10}},
	{{name = "explosive-cannon-shell", count = 5}},
	{{name = "piercing-shotgun-shell", count = 10}},
	{{name="piercing-rounds-magazine", count = 200}},
	{{name="tank", count = 1}},
	{{name="car", count = 1}},
	{{name="behemoth-biter", count = 1}},
	{{name="big-biter", count = 5}},
	{{name="big-spitter", count = 5}},
	{{name="big-worm-turret", count = 4}},
	{{name="slowdown-capsule", count = 10}},
	{{name="poison-capsule", count = 10}},
	{{name="grenade", count = 20}},
	{{name="land-mine", count = 20}},
	{{name="cluster-grenade", count = 5}},
	{{name="laser-turret", count = 2}},
	{
		{name="rocket-launcher", count = 1},
		{name="rocket", count = 1},
	},
	{
		{name="combat-shotgun", count = 1},
		{name="shotgun-shell",  count = 20},
	},
	{
		{name="flamethrower-turret", count = 1},
		{name="pipe", count = 100},
		{name="pipe-to-ground", count = 50},
		{name="storage-tank", count = 1},
		{name="storage-tank", count = 1},
		{name="pumpjack", count = 1},
	},
	{
		{name="roboport", count = 1},
		{name="fast-inserter", count = 20},
		{name="logistic-chest-requester", count = 50},
		{name="logistic-chest-storage", count = 10},
		{name="logistic-robot", count = 50},
		{name="construction-robot", count = 100},
	},
	{{name="rocket", count = 5}},
	{{name="explosive-rocket", count = 1}},
}
