return {
	"military",
	"logistics",
	"stone-wall",
	"gate",
	"gun-turret",
	"laser-turret",
	"logistic-robotics",
	"logistic-system",
	"heavy-armor",
	"construction-robotics",
	"optics",
	"optics-2", -- From another mod
	"optics-3", -- From another mod
	"cclp", -- From Color_Combinator_Lamp_Posts mod
	"automation",
	"electronics",
	"fast-inserter",
	"automation-2",
	"electric-energy-distribution-1",
	"steel-processing",
	"steel-axe",
	"textplates-steel", -- From textplates mod
	"engine",
	"railway",
	"automated-rail-signals",
	"automated-rail-transportation",
	"trainassembly-automated-train-assembling", -- From trainConstructionSite mod
	"trainfuel-2", -- From trainConstructionSite mod
	"rail-signals",
	"logistic-science-pack",
	"circuit-network",

	--- From IndustrialRevolution3
	"ir-charcoal",
	"ir-grinding",
	"ir-grinding-2",
	"ir-steambot",
	"ir-bronze-furnace",
	"ir-bronze-forestry",
	"ir-iron-forestry",
	"ir-research-1",
	"ir-gold-milestone",
	"ir-iron-milestone",
	"ir-steel-milestone",
	"ir-crude-oil-processing",
	"ir-light-oil-processing",
	"ir-heavy-oil-processing",
	"ir-lampbot",
	"ir-graphite",
	"ir-silicon",
	"ir-steam-power",
	"ir-petro-generator",
	"ir-electronics-1",
	"ir-iron-motor",
	"ir-coking",
}
